"""Add latitude and longitude to User model

Revision ID: 809a9aed5816
Revises: 
Create Date: 2024-05-26 17:35:17.651191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809a9aed5816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pickup_latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('destination_longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('destination_latitude', sa.Float(), nullable=False))
        batch_op.drop_column('pickup_area')
        batch_op.drop_column('destination_area')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_area', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('pickup_area', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('destination_latitude')
        batch_op.drop_column('destination_longitude')
        batch_op.drop_column('pickup_latitude')
        batch_op.drop_column('pickup_longitude')

    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
