"""migrate

Revision ID: b72c9a1f3308
Revises: f25efd53a950
Create Date: 2024-06-07 00:18:48.400239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b72c9a1f3308'
down_revision = 'f25efd53a950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ride_association')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_sum', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('num_ratings', sa.Float(), nullable=False))
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sqlite.JSON(), nullable=True))
        batch_op.drop_column('num_ratings')
        batch_op.drop_column('rating_sum')

    op.create_table('user_ride_association',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ride_id')
    )
    # ### end Alembic commands ###
